# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='Salient',
    version='0.1.0',
    description='Salient: A simple SqlAlchemy Linter.',
    python_requires='>=3.8',
    author='Tom Faulkner',
    author_email='faulkner@pm.me',
    entry_points={"console_scripts": ["salient = salient.salient:cmd"]},
    packages=['salient'],
    package_dir={"": "src"},
    package_data={},
    install_requires=[],
    extras_require={
        "dev": [
            "black==20.*,>=20.8.0.b1", "pytest==5.*,>=5.2.0",
            "pytest-asyncio==0.*,>=0.14.0"
        ]
    },
)
